package repository
import ("context"; "fmt"; "time"; "github.com/jackc/pgx/v5/pgtype"; "github.com/jackc/pgx/v5/pgxpool")
type PostgresContentRepository struct{db *pgxpool.Pool}
func NewPostgresContentRepository(db *pgxpool.Pool)*PostgresContentRepository{return &PostgresContentRepository{db:db}}
func(r *PostgresContentRepository)CreateEvent(ctx context.Context,u pgtype.UUID,s string,d time.Time,t string,desc *string)(Event,error){var e Event;err:=r.db.QueryRow(ctx,"INSERT INTO events (user_id,calendar_system_id,target_date,titulo,descripcion) VALUES ($1,$2,$3,$4,$5) RETURNING id,user_id,calendar_system_id,target_date,titulo,descripcion,created_at,updated_at",u,s,d,t,desc).Scan(&e.ID,&e.UserID,&e.CalendarSystemID,&e.TargetDate,&e.Title,&e.Description,&e.CreatedAt,&e.UpdatedAt);if err!=nil{return Event{},fmt.Errorf("create event: %w",err)};return e,nil}
func(r *PostgresContentRepository)ListEvents(ctx context.Context,u pgtype.UUID,from,to time.Time)([]Event,error){rows,err:=r.db.Query(ctx,"SELECT id,user_id,calendar_system_id,target_date,titulo,descripcion,created_at,updated_at FROM events WHERE user_id=$1 AND target_date >= $2 AND target_date < $3 ORDER BY target_date,created_at",u,from,to);if err!=nil{return nil,err};defer rows.Close();var out []Event;for rows.Next(){var e Event;if err:=rows.Scan(&e.ID,&e.UserID,&e.CalendarSystemID,&e.TargetDate,&e.Title,&e.Description,&e.CreatedAt,&e.UpdatedAt);err!=nil{return nil,err};out=append(out,e)};return out,rows.Err()}
func(r *PostgresContentRepository)DeleteEvent(ctx context.Context,u,id pgtype.UUID)error{tag,err:=r.db.Exec(ctx,"DELETE FROM events WHERE id=$1 AND user_id=$2",id,u);if err!=nil{return err};if tag.RowsAffected()==0{return ErrNotFound};return nil}
func(r *PostgresContentRepository)CreateInterpretation(ctx context.Context,u pgtype.UUID,s string,d time.Time,c string)(Interpretation,error){var i Interpretation;err:=r.db.QueryRow(ctx,"INSERT INTO interpretations (user_id,calendar_system_id,target_date,contenido) VALUES ($1,$2,$3,$4) RETURNING id,user_id,calendar_system_id,target_date,contenido,created_at,updated_at",u,s,d,c).Scan(&i.ID,&i.UserID,&i.CalendarSystemID,&i.TargetDate,&i.Content,&i.CreatedAt,&i.UpdatedAt);if err!=nil{return Interpretation{},fmt.Errorf("create interpretation: %w",err)};return i,nil}
func(r *PostgresContentRepository)ListInterpretations(ctx context.Context,s string,d time.Time)([]Interpretation,error){rows,err:=r.db.Query(ctx,"SELECT id,user_id,calendar_system_id,target_date,contenido,created_at,updated_at FROM interpretations WHERE calendar_system_id=$1 AND target_date=$2 ORDER BY created_at",s,d);if err!=nil{return nil,err};defer rows.Close();var out []Interpretation;for rows.Next(){var i Interpretation;if err:=rows.Scan(&i.ID,&i.UserID,&i.CalendarSystemID,&i.TargetDate,&i.Content,&i.CreatedAt,&i.UpdatedAt);err!=nil{return nil,err};out=append(out,i)};return out,rows.Err()}
