package repository
import("context";"errors";"time";"github.com/jackc/pgx/v5";"github.com/jackc/pgx/v5/pgxpool")
type PostgresULERepository struct{db *pgxpool.Pool}
func NewPostgresULERepository(db *pgxpool.Pool)*PostgresULERepository{return &PostgresULERepository{db:db}}
func(r *PostgresULERepository)ListArticles(c context.Context)([]Article,error){rows,e:=r.db.Query(c,"SELECT a.id,a.titulo,a.autor,a.fecha,a.resumen,a.contenido_html,a.imagen_destacada,a.imagen_alt,a.categoria,a.etiquetas,a.visible,COALESCE((SELECT array_agg(ab.bibliography_id ORDER BY ab.bibliography_id) FROM article_bibliography ab WHERE ab.article_id=a.id),'{}') FROM articles a WHERE visible=TRUE ORDER BY fecha DESC,id");if e!=nil{return nil,e};defer rows.Close();var out []Article;for rows.Next(){var x Article;if e=rows.Scan(&x.ID,&x.Titulo,&x.Autor,&x.Fecha,&x.Resumen,&x.ContenidoHTML,&x.ImagenDestacada,&x.ImagenAlt,&x.Categoria,&x.Etiquetas,&x.Visible,&x.BibliographyIDs);e!=nil{return nil,e};out=append(out,x)};return out,rows.Err()}
func(r *PostgresULERepository)GetArticle(c context.Context,id string)(Article,error){var x Article;e:=r.db.QueryRow(c,"SELECT a.id,a.titulo,a.autor,a.fecha,a.resumen,a.contenido_html,a.imagen_destacada,a.imagen_alt,a.categoria,a.etiquetas,a.visible,COALESCE((SELECT array_agg(ab.bibliography_id ORDER BY ab.bibliography_id) FROM article_bibliography ab WHERE ab.article_id=a.id),'{}') FROM articles a WHERE a.id=$1 AND a.visible=TRUE",id).Scan(&x.ID,&x.Titulo,&x.Autor,&x.Fecha,&x.Resumen,&x.ContenidoHTML,&x.ImagenDestacada,&x.ImagenAlt,&x.Categoria,&x.Etiquetas,&x.Visible,&x.BibliographyIDs);if errors.Is(e,pgx.ErrNoRows){return Article{},ErrNotFound};return x,e}
func(r *PostgresULERepository)ListBibliography(c context.Context)([]Bibliography,error){rows,e:=r.db.Query(c,"SELECT b.id,b.titulo,b.autores,b.anio,b.tipo,b.editorial,b.resumen,b.url,b.visible,COALESCE((SELECT array_agg(ab.article_id ORDER BY ab.article_id) FROM article_bibliography ab WHERE ab.bibliography_id=b.id),'{}') FROM bibliography b WHERE visible=TRUE ORDER BY anio DESC NULLS LAST,id");if e!=nil{return nil,e};defer rows.Close();var out []Bibliography;for rows.Next(){var x Bibliography;if e=rows.Scan(&x.ID,&x.Titulo,&x.Autores,&x.Anio,&x.Tipo,&x.Editorial,&x.Resumen,&x.URL,&x.Visible,&x.ArticleIDs);e!=nil{return nil,e};out=append(out,x)};return out,rows.Err()}
func(r *PostgresULERepository)GetBibliography(c context.Context,id string)(Bibliography,error){var x Bibliography;e:=r.db.QueryRow(c,"SELECT b.id,b.titulo,b.autores,b.anio,b.tipo,b.editorial,b.resumen,b.url,b.visible,COALESCE((SELECT array_agg(ab.article_id ORDER BY ab.article_id) FROM article_bibliography ab WHERE ab.bibliography_id=b.id),'{}') FROM bibliography b WHERE b.id=$1 AND b.visible=TRUE",id).Scan(&x.ID,&x.Titulo,&x.Autores,&x.Anio,&x.Tipo,&x.Editorial,&x.Resumen,&x.URL,&x.Visible,&x.ArticleIDs);if errors.Is(e,pgx.ErrNoRows){return Bibliography{},ErrNotFound};return x,e}
func(r *PostgresULERepository)ListCatalogs(c context.Context)([]Catalog,error){rows,e:=r.db.Query(c,"SELECT id,titulo,descripcion,imagen_portada,detalles,visible FROM catalogs WHERE visible=TRUE ORDER BY id");if e!=nil{return nil,e};defer rows.Close();var out []Catalog;for rows.Next(){var x Catalog;if e=rows.Scan(&x.ID,&x.Titulo,&x.Descripcion,&x.ImagenPortada,&x.Detalles,&x.Visible);e!=nil{return nil,e};out=append(out,x)};return out,rows.Err()}
func(r *PostgresULERepository)GetCatalog(c context.Context,id string)(Catalog,[]CatalogItem,error){var x Catalog;e:=r.db.QueryRow(c,"SELECT id,titulo,descripcion,imagen_portada,detalles,visible FROM catalogs WHERE id=$1 AND visible=TRUE",id).Scan(&x.ID,&x.Titulo,&x.Descripcion,&x.ImagenPortada,&x.Detalles,&x.Visible);if errors.Is(e,pgx.ErrNoRows){return Catalog{},nil,ErrNotFound};if e!=nil{return Catalog{},nil,e};rows,e:=r.db.Query(c,"SELECT id,catalog_id,titulo,imagen,detalles FROM catalog_items WHERE catalog_id=$1 ORDER BY id",id);if e!=nil{return Catalog{},nil,e};defer rows.Close();var items []CatalogItem;for rows.Next(){var i CatalogItem;if e=rows.Scan(&i.ID,&i.CatalogID,&i.Titulo,&i.Imagen,&i.Detalles);e!=nil{return Catalog{},nil,e};items=append(items,i)};return x,items,rows.Err()}
func(r *PostgresULERepository)ListAds(c context.Context,now time.Time)([]Ad,error){rows,e:=r.db.Query(c,"SELECT id,imagen,imagen_alt,contacto,slogan,descripcion,vigencia_inicio,vigencia_fin,activo,peso,enlace,tipo,paginas,prioridad_slot FROM ads WHERE activo=TRUE AND (vigencia_inicio IS NULL OR vigencia_inicio <= $1) AND (vigencia_fin IS NULL OR vigencia_fin >= $1) ORDER BY prioridad_slot NULLS LAST,peso DESC,id",now);if e!=nil{return nil,e};defer rows.Close();var out []Ad;for rows.Next(){var x Ad;if e=rows.Scan(&x.ID,&x.Imagen,&x.ImagenAlt,&x.Contacto,&x.Slogan,&x.Descripcion,&x.Inicio,&x.Fin,&x.Activo,&x.Peso,&x.Enlace,&x.Tipo,&x.Paginas,&x.PrioridadSlot);e!=nil{return nil,e};out=append(out,x)};return out,rows.Err()}

func (r *PostgresULERepository) CreateArticle(c context.Context,x Article)(Article,error){var out Article; e:=r.db.QueryRow(c,`INSERT INTO articles(id,titulo,autor,fecha,resumen,contenido_html,imagen_destacada,imagen_alt,categoria,etiquetas,visible) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id,titulo,autor,fecha,resumen,contenido_html,imagen_destacada,imagen_alt,categoria,etiquetas,visible`,x.ID,x.Titulo,x.Autor,x.Fecha,x.Resumen,x.ContenidoHTML,x.ImagenDestacada,x.ImagenAlt,x.Categoria,x.Etiquetas,x.Visible).Scan(&out.ID,&out.Titulo,&out.Autor,&out.Fecha,&out.Resumen,&out.ContenidoHTML,&out.ImagenDestacada,&out.ImagenAlt,&out.Categoria,&out.Etiquetas,&out.Visible);return out,e}
func (r *PostgresULERepository) UpdateArticle(c context.Context,id string,x Article)(Article,error){var out Article;e:=r.db.QueryRow(c,`UPDATE articles SET titulo=$2,autor=$3,fecha=$4,resumen=$5,contenido_html=$6,imagen_destacada=$7,imagen_alt=$8,categoria=$9,etiquetas=$10,visible=$11,updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING id,titulo,autor,fecha,resumen,contenido_html,imagen_destacada,imagen_alt,categoria,etiquetas,visible`,id,x.Titulo,x.Autor,x.Fecha,x.Resumen,x.ContenidoHTML,x.ImagenDestacada,x.ImagenAlt,x.Categoria,x.Etiquetas,x.Visible).Scan(&out.ID,&out.Titulo,&out.Autor,&out.Fecha,&out.Resumen,&out.ContenidoHTML,&out.ImagenDestacada,&out.ImagenAlt,&out.Categoria,&out.Etiquetas,&out.Visible);if errors.Is(e,pgx.ErrNoRows){return Article{},ErrNotFound};return out,e}
func (r *PostgresULERepository) DeleteArticle(c context.Context,id string)error{res,e:=r.db.Exec(c,"DELETE FROM articles WHERE id=$1",id);if e==nil&&res.RowsAffected()==0{return ErrNotFound};return e}
func (r *PostgresULERepository) SetArticleBibliography(c context.Context,id string,ids []string)error{tx,e:=r.db.Begin(c);if e!=nil{return e};defer tx.Rollback(c);if _,e=tx.Exec(c,"DELETE FROM article_bibliography WHERE article_id=$1",id);e!=nil{return e};for _,bid:=range ids{if _,e=tx.Exec(c,"INSERT INTO article_bibliography(article_id,bibliography_id) VALUES($1,$2)",id,bid);e!=nil{return e}};return tx.Commit(c)}

func (r *PostgresULERepository) CreateBibliography(c context.Context,x Bibliography)(Bibliography,error){var o Bibliography;e:=r.db.QueryRow(c,`INSERT INTO bibliography(id,titulo,autores,anio,tipo,editorial,resumen,url,visible) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,titulo,autores,anio,tipo,editorial,resumen,url,visible`,x.ID,x.Titulo,x.Autores,x.Anio,x.Tipo,x.Editorial,x.Resumen,x.URL,x.Visible).Scan(&o.ID,&o.Titulo,&o.Autores,&o.Anio,&o.Tipo,&o.Editorial,&o.Resumen,&o.URL,&o.Visible);return o,e}
func (r *PostgresULERepository) UpdateBibliography(c context.Context,id string,x Bibliography)(Bibliography,error){var o Bibliography;e:=r.db.QueryRow(c,`UPDATE bibliography SET titulo=$2,autores=$3,anio=$4,tipo=$5,editorial=$6,resumen=$7,url=$8,visible=$9,updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING id,titulo,autores,anio,tipo,editorial,resumen,url,visible`,id,x.Titulo,x.Autores,x.Anio,x.Tipo,x.Editorial,x.Resumen,x.URL,x.Visible).Scan(&o.ID,&o.Titulo,&o.Autores,&o.Anio,&o.Tipo,&o.Editorial,&o.Resumen,&o.URL,&o.Visible);if errors.Is(e,pgx.ErrNoRows){return Bibliography{},ErrNotFound};return o,e}
func (r *PostgresULERepository) DeleteBibliography(c context.Context,id string)error{tag,e:=r.db.Exec(c,"DELETE FROM bibliography WHERE id=$1",id);if e==nil&&tag.RowsAffected()==0{return ErrNotFound};return e}
func (r *PostgresULERepository) CreateCatalog(c context.Context,x Catalog)(Catalog,error){var o Catalog;e:=r.db.QueryRow(c,`INSERT INTO catalogs(id,titulo,descripcion,imagen_portada,detalles,visible) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,titulo,descripcion,imagen_portada,detalles,visible`,x.ID,x.Titulo,x.Descripcion,x.ImagenPortada,x.Detalles,x.Visible).Scan(&o.ID,&o.Titulo,&o.Descripcion,&o.ImagenPortada,&o.Detalles,&o.Visible);return o,e}
func (r *PostgresULERepository) UpdateCatalog(c context.Context,id string,x Catalog)(Catalog,error){var o Catalog;e:=r.db.QueryRow(c,`UPDATE catalogs SET titulo=$2,descripcion=$3,imagen_portada=$4,detalles=$5,visible=$6,updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING id,titulo,descripcion,imagen_portada,detalles,visible`,id,x.Titulo,x.Descripcion,x.ImagenPortada,x.Detalles,x.Visible).Scan(&o.ID,&o.Titulo,&o.Descripcion,&o.ImagenPortada,&o.Detalles,&o.Visible);if errors.Is(e,pgx.ErrNoRows){return Catalog{},ErrNotFound};return o,e}
func (r *PostgresULERepository) DeleteCatalog(c context.Context,id string)error{tag,e:=r.db.Exec(c,"DELETE FROM catalogs WHERE id=$1",id);if e==nil&&tag.RowsAffected()==0{return ErrNotFound};return e}
func (r *PostgresULERepository) CreateCatalogItem(c context.Context,x CatalogItem)(CatalogItem,error){var o CatalogItem;e:=r.db.QueryRow(c,`INSERT INTO catalog_items(id,catalog_id,titulo,imagen,detalles) VALUES($1,$2,$3,$4,$5) RETURNING id,catalog_id,titulo,imagen,detalles`,x.ID,x.CatalogID,x.Titulo,x.Imagen,x.Detalles).Scan(&o.ID,&o.CatalogID,&o.Titulo,&o.Imagen,&o.Detalles);return o,e}
func (r *PostgresULERepository) UpdateCatalogItem(c context.Context,cid,id string,x CatalogItem)(CatalogItem,error){var o CatalogItem;e:=r.db.QueryRow(c,`UPDATE catalog_items SET titulo=$3,imagen=$4,detalles=$5 WHERE catalog_id=$1 AND id=$2 RETURNING id,catalog_id,titulo,imagen,detalles`,cid,id,x.Titulo,x.Imagen,x.Detalles).Scan(&o.ID,&o.CatalogID,&o.Titulo,&o.Imagen,&o.Detalles);if errors.Is(e,pgx.ErrNoRows){return CatalogItem{},ErrNotFound};return o,e}
func (r *PostgresULERepository) DeleteCatalogItem(c context.Context,cid,id string)error{tag,e:=r.db.Exec(c,"DELETE FROM catalog_items WHERE catalog_id=$1 AND id=$2",cid,id);if e==nil&&tag.RowsAffected()==0{return ErrNotFound};return e}
func (r *PostgresULERepository) CreateAd(c context.Context,x Ad)(Ad,error){var o Ad;e:=r.db.QueryRow(c,`INSERT INTO ads(id,imagen,imagen_alt,contacto,slogan,descripcion,vigencia_inicio,vigencia_fin,activo,peso,enlace,tipo,paginas,prioridad_slot) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING id,imagen,imagen_alt,contacto,slogan,descripcion,vigencia_inicio,vigencia_fin,activo,peso,enlace,tipo,paginas,prioridad_slot`,x.ID,x.Imagen,x.ImagenAlt,x.Contacto,x.Slogan,x.Descripcion,x.Inicio,x.Fin,x.Activo,x.Peso,x.Enlace,x.Tipo,x.Paginas,x.PrioridadSlot).Scan(&o.ID,&o.Imagen,&o.ImagenAlt,&o.Contacto,&o.Slogan,&o.Descripcion,&o.Inicio,&o.Fin,&o.Activo,&o.Peso,&o.Enlace,&o.Tipo,&o.Paginas,&o.PrioridadSlot);return o,e}
func (r *PostgresULERepository) UpdateAd(c context.Context,id string,x Ad)(Ad,error){var o Ad;e:=r.db.QueryRow(c,`UPDATE ads SET imagen=$2,imagen_alt=$3,contacto=$4,slogan=$5,descripcion=$6,vigencia_inicio=$7,vigencia_fin=$8,activo=$9,peso=$10,enlace=$11,tipo=$12,paginas=$13,prioridad_slot=$14,updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING id,imagen,imagen_alt,contacto,slogan,descripcion,vigencia_inicio,vigencia_fin,activo,peso,enlace,tipo,paginas,prioridad_slot`,id,x.Imagen,x.ImagenAlt,x.Contacto,x.Slogan,x.Descripcion,x.Inicio,x.Fin,x.Activo,x.Peso,x.Enlace,x.Tipo,x.Paginas,x.PrioridadSlot).Scan(&o.ID,&o.Imagen,&o.ImagenAlt,&o.Contacto,&o.Slogan,&o.Descripcion,&o.Inicio,&o.Fin,&o.Activo,&o.Peso,&o.Enlace,&o.Tipo,&o.Paginas,&o.PrioridadSlot);if errors.Is(e,pgx.ErrNoRows){return Ad{},ErrNotFound};return o,e}
func (r *PostgresULERepository) DeleteAd(c context.Context,id string)error{tag,e:=r.db.Exec(c,"DELETE FROM ads WHERE id=$1",id);if e==nil&&tag.RowsAffected()==0{return ErrNotFound};return e}
