package repository
import("context";"errors";"time";"github.com/jackc/pgx/v5";"github.com/jackc/pgx/v5/pgxpool")
type PostgresULERepository struct{db *pgxpool.Pool}
func NewPostgresULERepository(db *pgxpool.Pool)*PostgresULERepository{return &PostgresULERepository{db:db}}
func(r *PostgresULERepository)ListArticles(c context.Context)([]Article,error){rows,e:=r.db.Query(c,"SELECT a.id,a.titulo,a.autor,a.fecha,a.resumen,a.contenido_html,a.imagen_destacada,a.imagen_alt,a.categoria,a.etiquetas,a.visible,COALESCE((SELECT array_agg(ab.bibliography_id ORDER BY ab.bibliography_id) FROM article_bibliography ab WHERE ab.article_id=a.id),'{}') FROM articles a WHERE visible=TRUE ORDER BY fecha DESC,id");if e!=nil{return nil,e};defer rows.Close();var out []Article;for rows.Next(){var x Article;if e=rows.Scan(&x.ID,&x.Titulo,&x.Autor,&x.Fecha,&x.Resumen,&x.ContenidoHTML,&x.ImagenDestacada,&x.ImagenAlt,&x.Categoria,&x.Etiquetas,&x.Visible,&x.BibliographyIDs);e!=nil{return nil,e};out=append(out,x)};return out,rows.Err()}
func(r *PostgresULERepository)GetArticle(c context.Context,id string)(Article,error){var x Article;e:=r.db.QueryRow(c,"SELECT a.id,a.titulo,a.autor,a.fecha,a.resumen,a.contenido_html,a.imagen_destacada,a.imagen_alt,a.categoria,a.etiquetas,a.visible,COALESCE((SELECT array_agg(ab.bibliography_id ORDER BY ab.bibliography_id) FROM article_bibliography ab WHERE ab.article_id=a.id),'{}') FROM articles a WHERE a.id=$1 AND a.visible=TRUE",id).Scan(&x.ID,&x.Titulo,&x.Autor,&x.Fecha,&x.Resumen,&x.ContenidoHTML,&x.ImagenDestacada,&x.ImagenAlt,&x.Categoria,&x.Etiquetas,&x.Visible,&x.BibliographyIDs);if errors.Is(e,pgx.ErrNoRows){return Article{},ErrNotFound};return x,e}
func(r *PostgresULERepository)ListBibliography(c context.Context)([]Bibliography,error){rows,e:=r.db.Query(c,"SELECT b.id,b.titulo,b.autores,b.anio,b.tipo,b.editorial,b.resumen,b.url,b.visible,COALESCE((SELECT array_agg(ab.article_id ORDER BY ab.article_id) FROM article_bibliography ab WHERE ab.bibliography_id=b.id),'{}') FROM bibliography b WHERE visible=TRUE ORDER BY anio DESC NULLS LAST,id");if e!=nil{return nil,e};defer rows.Close();var out []Bibliography;for rows.Next(){var x Bibliography;if e=rows.Scan(&x.ID,&x.Titulo,&x.Autores,&x.Anio,&x.Tipo,&x.Editorial,&x.Resumen,&x.URL,&x.Visible,&x.ArticleIDs);e!=nil{return nil,e};out=append(out,x)};return out,rows.Err()}
func(r *PostgresULERepository)GetBibliography(c context.Context,id string)(Bibliography,error){var x Bibliography;e:=r.db.QueryRow(c,"SELECT b.id,b.titulo,b.autores,b.anio,b.tipo,b.editorial,b.resumen,b.url,b.visible,COALESCE((SELECT array_agg(ab.article_id ORDER BY ab.article_id) FROM article_bibliography ab WHERE ab.bibliography_id=b.id),'{}') FROM bibliography b WHERE b.id=$1 AND b.visible=TRUE",id).Scan(&x.ID,&x.Titulo,&x.Autores,&x.Anio,&x.Tipo,&x.Editorial,&x.Resumen,&x.URL,&x.Visible,&x.ArticleIDs);if errors.Is(e,pgx.ErrNoRows){return Bibliography{},ErrNotFound};return x,e}
func(r *PostgresULERepository)ListCatalogs(c context.Context)([]Catalog,error){rows,e:=r.db.Query(c,"SELECT id,titulo,descripcion,imagen_portada,detalles,visible FROM catalogs WHERE visible=TRUE ORDER BY id");if e!=nil{return nil,e};defer rows.Close();var out []Catalog;for rows.Next(){var x Catalog;if e=rows.Scan(&x.ID,&x.Titulo,&x.Descripcion,&x.ImagenPortada,&x.Detalles,&x.Visible);e!=nil{return nil,e};out=append(out,x)};return out,rows.Err()}
func(r *PostgresULERepository)GetCatalog(c context.Context,id string)(Catalog,[]CatalogItem,error){var x Catalog;e:=r.db.QueryRow(c,"SELECT id,titulo,descripcion,imagen_portada,detalles,visible FROM catalogs WHERE id=$1 AND visible=TRUE",id).Scan(&x.ID,&x.Titulo,&x.Descripcion,&x.ImagenPortada,&x.Detalles,&x.Visible);if errors.Is(e,pgx.ErrNoRows){return Catalog{},nil,ErrNotFound};if e!=nil{return Catalog{},nil,e};rows,e:=r.db.Query(c,"SELECT id,catalog_id,titulo,imagen,detalles FROM catalog_items WHERE catalog_id=$1 ORDER BY id",id);if e!=nil{return Catalog{},nil,e};defer rows.Close();var items []CatalogItem;for rows.Next(){var i CatalogItem;if e=rows.Scan(&i.ID,&i.CatalogID,&i.Titulo,&i.Imagen,&i.Detalles);e!=nil{return Catalog{},nil,e};items=append(items,i)};return x,items,rows.Err()}
func(r *PostgresULERepository)ListAds(c context.Context,now time.Time)([]Ad,error){rows,e:=r.db.Query(c,"SELECT id,imagen,imagen_alt,contacto,slogan,descripcion,vigencia_inicio,vigencia_fin,activo,peso,enlace,tipo,paginas,prioridad_slot FROM ads WHERE activo=TRUE AND (vigencia_inicio IS NULL OR vigencia_inicio <= $1) AND (vigencia_fin IS NULL OR vigencia_fin >= $1) ORDER BY prioridad_slot NULLS LAST,peso DESC,id",now);if e!=nil{return nil,e};defer rows.Close();var out []Ad;for rows.Next(){var x Ad;if e=rows.Scan(&x.ID,&x.Imagen,&x.ImagenAlt,&x.Contacto,&x.Slogan,&x.Descripcion,&x.Inicio,&x.Fin,&x.Activo,&x.Peso,&x.Enlace,&x.Tipo,&x.Paginas,&x.PrioridadSlot);e!=nil{return nil,e};out=append(out,x)};return out,rows.Err()}
