package handlers
import ("encoding/json"; "net/http"; "strings"; "time"; "github.com/jackc/pgx/v5/pgtype"; "github.com/utopia-development/tonalmaster_backend/internal/repository"; "github.com/utopia-development/tonalmaster_backend/internal/services")
type ContentHandler struct{service *services.ContentService}
func NewContentHandler(s *services.ContentService)*ContentHandler{return &ContentHandler{service:s}}
type eventRequest struct{CalendarSystemID string `json:"calendar_system_id"`; TargetDate string `json:"target_date"`; Title string `json:"titulo"`; Description *string `json:"descripcion,omitempty"`}
type interpretationRequest struct{CalendarSystemID string `json:"calendar_system_id"`; TargetDate string `json:"target_date"`; Content string `json:"contenido"`}
func parseUUID(v string)(pgtype.UUID,error){var id pgtype.UUID;err:=id.Scan(v);return id,err}
func parseDate(v string)(time.Time,error){return time.Parse("2006-01-02",v)}
func eventDTO(e repository.Event)map[string]any{return map[string]any{"id":e.ID.String(),"calendar_system_id":e.CalendarSystemID,"target_date":e.TargetDate.Format("2006-01-02"),"titulo":e.Title,"descripcion":e.Description,"created_at":e.CreatedAt.UTC().Format(time.RFC3339),"updated_at":e.UpdatedAt.UTC().Format(time.RFC3339)}}
func interpretationDTO(i repository.Interpretation)map[string]any{return map[string]any{"id":i.ID.String(),"user_id":i.UserID.String(),"calendar_system_id":i.CalendarSystemID,"target_date":i.TargetDate.Format("2006-01-02"),"contenido":i.Content,"created_at":i.CreatedAt.UTC().Format(time.RFC3339),"updated_at":i.UpdatedAt.UTC().Format(time.RFC3339)}}
func(h *ContentHandler)CreateEvent(w http.ResponseWriter,r *http.Request){u,ok:=currentUser(r);if !ok{writeError(w,401,"unauthorized","authentication required");return};var q eventRequest;if json.NewDecoder(r.Body).Decode(&q)!=nil||q.CalendarSystemID==""||q.Title==""{writeError(w,400,"invalid_request","calendar_system_id, target_date and titulo are required");return};d,err:=parseDate(q.TargetDate);if err!=nil{writeError(w,400,"invalid_date","target_date must use YYYY-MM-DD");return};e,err:=h.service.CreateEvent(r.Context(),u.ID,q.CalendarSystemID,d,strings.TrimSpace(q.Title),q.Description);if err!=nil{writeError(w,400,"event_create_failed","could not create event");return};writeJSON(w,201,eventDTO(e))}
func(h *ContentHandler)ListEvents(w http.ResponseWriter,r *http.Request){u,ok:=currentUser(r);if !ok{writeError(w,401,"unauthorized","authentication required");return};from:=time.Now().UTC().Truncate(24*time.Hour);if v:=r.URL.Query().Get("from");v!=""{d,e:=parseDate(v);if e!=nil{writeError(w,400,"invalid_date","from must use YYYY-MM-DD");return};from=d};to:=from.AddDate(0,0,31);if v:=r.URL.Query().Get("to");v!=""{d,e:=parseDate(v);if e!=nil{writeError(w,400,"invalid_date","to must use YYYY-MM-DD");return};to=d.AddDate(0,0,1)};items,err:=h.service.ListEvents(r.Context(),u.ID,from,to);if err!=nil{writeError(w,500,"events_failed","could not list events");return};out:=make([]map[string]any,0,len(items));for _,e:=range items{out=append(out,eventDTO(e))};writeJSON(w,200,out)}
func(h *ContentHandler)DeleteEvent(w http.ResponseWriter,r *http.Request){u,ok:=currentUser(r);if !ok{writeError(w,401,"unauthorized","authentication required");return};id,err:=parseUUID(r.PathValue("id"));if err!=nil{writeError(w,400,"invalid_id","id must be a UUID");return};if err:=h.service.DeleteEvent(r.Context(),u.ID,id);err!=nil{writeError(w,404,"event_not_found","event not found");return};w.WriteHeader(204)}
func(h *ContentHandler)CreateInterpretation(w http.ResponseWriter,r *http.Request){u,ok:=currentUser(r);if !ok{writeError(w,401,"unauthorized","authentication required");return};var q interpretationRequest;if json.NewDecoder(r.Body).Decode(&q)!=nil||q.CalendarSystemID==""||q.Content==""{writeError(w,400,"invalid_request","calendar_system_id, target_date and contenido are required");return};d,err:=parseDate(q.TargetDate);if err!=nil{writeError(w,400,"invalid_date","target_date must use YYYY-MM-DD");return};i,err:=h.service.CreateInterpretation(r.Context(),u.ID,q.CalendarSystemID,d,q.Content);if err!=nil{writeError(w,400,"interpretation_create_failed","could not create interpretation");return};writeJSON(w,201,interpretationDTO(i))}
func(h *ContentHandler)ListInterpretations(w http.ResponseWriter,r *http.Request){sys:=r.URL.Query().Get("system");ds:=r.URL.Query().Get("date");if sys==""||ds==""{writeError(w,400,"invalid_request","system and date are required");return};d,err:=parseDate(ds);if err!=nil{writeError(w,400,"invalid_date","date must use YYYY-MM-DD");return};items,err:=h.service.ListInterpretations(r.Context(),sys,d);if err!=nil{writeError(w,500,"interpretations_failed","could not list interpretations");return};out:=make([]map[string]any,0,len(items));for _,i:=range items{out=append(out,interpretationDTO(i))};writeJSON(w,200,out)}
