package handlers

import (
 "encoding/json"
 "net/http"
 "time"
 "github.com/utopia-development/tonalmaster_backend/internal/repository"
 "github.com/utopia-development/tonalmaster_backend/internal/services"
)

type EditorialHandler struct{s *services.EditorialService}
func NewEditorialHandler(s *services.EditorialService)*EditorialHandler{return &EditorialHandler{s:s}}
func(h *EditorialHandler)auth(w http.ResponseWriter,r *http.Request)(repository.User,bool){u,ok:=currentUser(r);if !ok||!h.s.IsAuthorized(u.Role){writeError(w,http.StatusForbidden,"forbidden","editorial permission required");return repository.User{},false};return u,true}
type articleRequest struct{ID,Titulo string; Autor *string; Fecha string; Resumen,ContenidoHTML string; ImagenDestacada,ImagenAlt,Categoria *string; Etiquetas []string; Visible bool; BibliographyIDs []string}
func articleFrom(q articleRequest)(repository.Article,error){d,e:=time.Parse("2006-01-02",q.Fecha);return repository.Article{ID:q.ID,Titulo:q.Titulo,Autor:q.Autor,Fecha:d,Resumen:q.Resumen,ContenidoHTML:q.ContenidoHTML,ImagenDestacada:q.ImagenDestacada,ImagenAlt:q.ImagenAlt,Categoria:q.Categoria,Etiquetas:q.Etiquetas,Visible:q.Visible,BibliographyIDs:q.BibliographyIDs},e}
func(h *EditorialHandler)CreateArticle(w http.ResponseWriter,r *http.Request){u,ok:=h.auth(w,r);_ = u;if !ok{return};var q articleRequest;if json.NewDecoder(r.Body).Decode(&q)!=nil||q.ID==""||q.Titulo==""||q.Fecha==""||q.Resumen==""||q.ContenidoHTML==""{writeError(w,400,"invalid_request","id, titulo, fecha, resumen and contenido_html are required");return};x,e:=articleFrom(q);if e!=nil{writeError(w,400,"invalid_date","fecha must use YYYY-MM-DD");return};x,e=h.s.CreateArticle(r.Context(),u.Role,x);if e!=nil{writeError(w,400,"article_create_failed","could not create article");return};writeJSON(w,201,x)}
func(h *EditorialHandler)UpdateArticle(w http.ResponseWriter,r *http.Request){u,ok:=h.auth(w,r);if !ok{return};var q articleRequest;if json.NewDecoder(r.Body).Decode(&q)!=nil{writeError(w,400,"invalid_request","invalid JSON");return};q.ID=r.PathValue("id");x,e:=articleFrom(q);if e!=nil{writeError(w,400,"invalid_date","fecha must use YYYY-MM-DD");return};x,e=h.s.UpdateArticle(r.Context(),u.Role,q.ID,x);if e==repository.ErrNotFound{writeError(w,404,"article_not_found","article not found");return};if e!=nil{writeError(w,400,"article_update_failed","could not update article");return};writeJSON(w,200,x)}
func(h *EditorialHandler)DeleteArticle(w http.ResponseWriter,r *http.Request){u,ok:=h.auth(w,r);if !ok{return};e:=h.s.DeleteArticle(r.Context(),u.Role,r.PathValue("id"));if e==repository.ErrNotFound{writeError(w,404,"article_not_found","article not found");return};if e!=nil{writeError(w,500,"article_delete_failed","could not delete article");return};w.WriteHeader(204)}
type bibliographyRequest struct{ID,Titulo string; Autores []string; Anio *int; Tipo string; Editorial,Resumen,URL *string; Visible bool; ArticleIDs []string}
func(h *EditorialHandler)CreateBibliography(w http.ResponseWriter,r *http.Request){u,ok:=h.auth(w,r);if !ok{return};var q bibliographyRequest;if json.NewDecoder(r.Body).Decode(&q)!=nil||q.ID==""||q.Titulo==""||q.Tipo==""{writeError(w,400,"invalid_request","id, titulo and tipo are required");return};x:=repository.Bibliography{ID:q.ID,Titulo:q.Titulo,Autores:q.Autores,Anio:q.Anio,Tipo:q.Tipo,Editorial:q.Editorial,Resumen:q.Resumen,URL:q.URL,Visible:q.Visible,ArticleIDs:q.ArticleIDs};x,e:=h.s.CreateBibliography(r.Context(),u.Role,x);if e!=nil{writeError(w,400,"bibliography_create_failed","could not create bibliography");return};writeJSON(w,201,x)}
func(h *EditorialHandler)UpdateBibliography(w http.ResponseWriter,r *http.Request){u,ok:=h.auth(w,r);if !ok{return};var q bibliographyRequest;if json.NewDecoder(r.Body).Decode(&q)!=nil{writeError(w,400,"invalid_request","invalid JSON");return};x:=repository.Bibliography{ID:r.PathValue("id"),Titulo:q.Titulo,Autores:q.Autores,Anio:q.Anio,Tipo:q.Tipo,Editorial:q.Editorial,Resumen:q.Resumen,URL:q.URL,Visible:q.Visible};x,e:=h.s.UpdateBibliography(r.Context(),u.Role,x.ID,x);if e==repository.ErrNotFound{writeError(w,404,"bibliography_not_found","not found");return};if e!=nil{writeError(w,400,"bibliography_update_failed","could not update");return};writeJSON(w,200,x)}
func(h *EditorialHandler)DeleteBibliography(w http.ResponseWriter,r *http.Request){u,ok:=h.auth(w,r);if !ok{return};e:=h.s.DeleteBibliography(r.Context(),u.Role,r.PathValue("id"));if e==repository.ErrNotFound{writeError(w,404,"bibliography_not_found","not found");return};if e!=nil{writeError(w,500,"bibliography_delete_failed","could not delete");return};w.WriteHeader(204)}
type catalogRequest struct{ID,Titulo string;Descripcion,ImagenPortada *string;Detalles json.RawMessage;Visible bool}
func(h *EditorialHandler)CreateCatalog(w http.ResponseWriter,r *http.Request){u,ok:=h.auth(w,r);if !ok{return};var q catalogRequest;if json.NewDecoder(r.Body).Decode(&q)!=nil||q.ID==""||q.Titulo==""{writeError(w,400,"invalid_request","id and titulo are required");return};if len(q.Detalles)==0{q.Detalles=[]byte("{}")};x,e:=h.s.CreateCatalog(r.Context(),u.Role,repository.Catalog{ID:q.ID,Titulo:q.Titulo,Descripcion:q.Descripcion,ImagenPortada:q.ImagenPortada,Detalles:q.Detalles,Visible:q.Visible});if e!=nil{writeError(w,400,"catalog_create_failed","could not create catalog");return};writeJSON(w,201,x)}
func(h *EditorialHandler)UpdateCatalog(w http.ResponseWriter,r *http.Request){u,ok:=h.auth(w,r);if !ok{return};var q catalogRequest;if json.NewDecoder(r.Body).Decode(&q)!=nil{writeError(w,400,"invalid_request","invalid JSON");return};if len(q.Detalles)==0{q.Detalles=[]byte("{}")};x,e:=h.s.UpdateCatalog(r.Context(),u.Role,r.PathValue("id"),repository.Catalog{ID:r.PathValue("id"),Titulo:q.Titulo,Descripcion:q.Descripcion,ImagenPortada:q.ImagenPortada,Detalles:q.Detalles,Visible:q.Visible});if e==repository.ErrNotFound{writeError(w,404,"catalog_not_found","not found");return};if e!=nil{writeError(w,400,"catalog_update_failed","could not update");return};writeJSON(w,200,x)}
func(h *EditorialHandler)DeleteCatalog(w http.ResponseWriter,r *http.Request){u,ok:=h.auth(w,r);if !ok{return};e:=h.s.DeleteCatalog(r.Context(),u.Role,r.PathValue("id"));if e==repository.ErrNotFound{writeError(w,404,"catalog_not_found","not found");return};if e!=nil{writeError(w,500,"catalog_delete_failed","could not delete");return};w.WriteHeader(204)}
type itemRequest struct{ID,Titulo,Imagen string;Detalles json.RawMessage}
func(h *EditorialHandler)CreateItem(w http.ResponseWriter,r *http.Request){u,ok:=h.auth(w,r);if !ok{return};var q itemRequest;if json.NewDecoder(r.Body).Decode(&q)!=nil||q.ID==""||q.Titulo==""||q.Imagen==""{writeError(w,400,"invalid_request","id, titulo and imagen are required");return};if len(q.Detalles)==0{q.Detalles=[]byte("{}")};x,e:=h.s.CreateCatalogItem(r.Context(),u.Role,repository.CatalogItem{ID:q.ID,CatalogID:r.PathValue("id"),Titulo:q.Titulo,Imagen:q.Imagen,Detalles:q.Detalles});if e!=nil{writeError(w,400,"item_create_failed","could not create item");return};writeJSON(w,201,x)}
func(h *EditorialHandler)UpdateItem(w http.ResponseWriter,r *http.Request){u,ok:=h.auth(w,r);if !ok{return};var q itemRequest;if json.NewDecoder(r.Body).Decode(&q)!=nil{writeError(w,400,"invalid_request","invalid JSON");return};if len(q.Detalles)==0{q.Detalles=[]byte("{}")};x,e:=h.s.UpdateCatalogItem(r.Context(),u.Role,r.PathValue("id"),r.PathValue("item_id"),repository.CatalogItem{ID:r.PathValue("item_id"),CatalogID:r.PathValue("id"),Titulo:q.Titulo,Imagen:q.Imagen,Detalles:q.Detalles});if e==repository.ErrNotFound{writeError(w,404,"item_not_found","not found");return};if e!=nil{writeError(w,400,"item_update_failed","could not update");return};writeJSON(w,200,x)}
func(h *EditorialHandler)DeleteItem(w http.ResponseWriter,r *http.Request){u,ok:=h.auth(w,r);if !ok{return};e:=h.s.DeleteCatalogItem(r.Context(),u.Role,r.PathValue("id"),r.PathValue("item_id"));if e==repository.ErrNotFound{writeError(w,404,"item_not_found","not found");return};if e!=nil{writeError(w,500,"item_delete_failed","could not delete");return};w.WriteHeader(204)}
type adRequest struct{ID string `json:"id"`;Imagen,ImagenAlt,Contacto,Slogan,Descripcion *string;Inicio,Fin *string;Activo bool;Peso int;Enlace *string;Tipo string;Paginas []string;PrioridadSlot *string}
func(h *EditorialHandler)CreateAd(w http.ResponseWriter,r *http.Request){u,ok:=h.auth(w,r);if !ok{return};var q adRequest;if json.NewDecoder(r.Body).Decode(&q)!=nil{writeError(w,400,"invalid_request","invalid JSON");return};if q.ID==""{writeError(w,400,"invalid_request","id is required");return};x,e:=parseAd(q,q.ID);if e!=nil{writeError(w,400,"invalid_request",e.Error());return};x,e=h.s.CreateAd(r.Context(),u.Role,x);if e!=nil{writeError(w,400,"ad_create_failed","could not create ad");return};writeJSON(w,201,x)}
func parseAd(q adRequest,id string)(repository.Ad,error){var a repository.Ad;a.ID=id;a.Imagen=q.Imagen;a.ImagenAlt=q.ImagenAlt;a.Contacto=q.Contacto;a.Slogan=q.Slogan;a.Descripcion=q.Descripcion;a.Activo=q.Activo;a.Peso=q.Peso;a.Enlace=q.Enlace;a.Tipo=q.Tipo;a.Paginas=q.Paginas;a.PrioridadSlot=q.PrioridadSlot;if q.Peso==0{a.Peso=1};var e error;if q.Inicio!=nil && *q.Inicio!=""{d,e:=time.Parse("2006-01-02",*q.Inicio);if e!=nil{return a,e};a.Inicio=&d};if q.Fin!=nil && *q.Fin!=""{d,e:=time.Parse("2006-01-02",*q.Fin);if e!=nil{return a,e};a.Fin=&d};return a,nil}
func(h *EditorialHandler)UpdateAd(w http.ResponseWriter,r *http.Request){u,ok:=h.auth(w,r);if !ok{return};var q adRequest;if json.NewDecoder(r.Body).Decode(&q)!=nil{writeError(w,400,"invalid_request","invalid JSON");return};x,e:=parseAd(q,r.PathValue("id"));if e!=nil{writeError(w,400,"invalid_request",e.Error());return};x,e=h.s.UpdateAd(r.Context(),u.Role,x.ID,x);if e==repository.ErrNotFound{writeError(w,404,"ad_not_found","not found");return};if e!=nil{writeError(w,400,"ad_update_failed","could not update");return};writeJSON(w,200,x)}
func(h *EditorialHandler)DeleteAd(w http.ResponseWriter,r *http.Request){u,ok:=h.auth(w,r);if !ok{return};e:=h.s.DeleteAd(r.Context(),u.Role,r.PathValue("id"));if e==repository.ErrNotFound{writeError(w,404,"ad_not_found","not found");return};if e!=nil{writeError(w,500,"ad_delete_failed","could not delete");return};w.WriteHeader(204)}
