package handlers
import("net/http";"github.com/utopia-development/tonalmaster_backend/internal/repository";"github.com/utopia-development/tonalmaster_backend/internal/services")
type ULEHandler struct{s *services.ULEService}
func NewULEHandler(s *services.ULEService)*ULEHandler{return &ULEHandler{s:s}}
func(h *ULEHandler)Articles(w http.ResponseWriter,r *http.Request){v,e:=h.s.Articles(r.Context());if e!=nil{writeError(w,500,"articles_failed","could not load articles");return};out:=make([]map[string]any,0,len(v));for _,x:=range v{out=append(out,servicesArticleDTO(x))};writeJSON(w,200,out)}
func(h *ULEHandler)Article(w http.ResponseWriter,r *http.Request){x,e:=h.s.Article(r.Context(),r.PathValue("id"));if e==repository.ErrNotFound{writeError(w,404,"article_not_found","article not found");return};if e!=nil{writeError(w,500,"article_failed","could not load article");return};writeJSON(w,200,servicesArticleDTO(x))}
func(h *ULEHandler)Bibliography(w http.ResponseWriter,r *http.Request){v,e:=h.s.Bibliography(r.Context());if e!=nil{writeError(w,500,"bibliography_failed","could not load bibliography");return};out:=make([]map[string]any,0,len(v));for _,x:=range v{out=append(out,servicesBiblioDTO(x))};writeJSON(w,200,out)}
func(h *ULEHandler)Biblio(w http.ResponseWriter,r *http.Request){x,e:=h.s.Biblio(r.Context(),r.PathValue("id"));if e==repository.ErrNotFound{writeError(w,404,"bibliography_not_found","bibliography entry not found");return};if e!=nil{writeError(w,500,"bibliography_failed","could not load bibliography entry");return};writeJSON(w,200,servicesBiblioDTO(x))}
func(h *ULEHandler)Catalogs(w http.ResponseWriter,r *http.Request){v,e:=h.s.Catalogs(r.Context());if e!=nil{writeError(w,500,"catalogs_failed","could not load catalogs");return};out:=make([]map[string]any,0,len(v));for _,x:=range v{out=append(out,servicesCatalogDTO(x,nil))};writeJSON(w,200,out)}
func(h *ULEHandler)Catalog(w http.ResponseWriter,r *http.Request){x,items,e:=h.s.Catalog(r.Context(),r.PathValue("id"));if e==repository.ErrNotFound{writeError(w,404,"catalog_not_found","catalog not found");return};if e!=nil{writeError(w,500,"catalog_failed","could not load catalog");return};writeJSON(w,200,servicesCatalogDTO(x,items))}
func(h *ULEHandler)Ads(w http.ResponseWriter,r *http.Request){v,e:=h.s.Ads(r.Context());if e!=nil{writeError(w,500,"ads_failed","could not load ads");return};out:=make([]map[string]any,0,len(v));for _,x:=range v{out=append(out,servicesAdDTO(x))};writeJSON(w,200,out)}
var servicesArticleDTO=servicesArticleDTOShim
var servicesBiblioDTO=servicesBiblioDTOShim
var servicesCatalogDTO=servicesCatalogDTOShim
var servicesAdDTO=servicesAdDTOShim
func servicesArticleDTOShim(x repository.Article)map[string]any{return map[string]any{"id":x.ID,"titulo":x.Titulo,"autor":deref(x.Autor),"fecha":x.Fecha.Format("2006-01-02"),"resumen":x.Resumen,"contenido_html":x.ContenidoHTML,"imagen_destacada":deref(x.ImagenDestacada),"imagen_alt":deref(x.ImagenAlt),"categoria":deref(x.Categoria),"etiquetas":x.Etiquetas,"bibliografía_relacionada":[]string{},"visible":x.Visible}}
func servicesBiblioDTOShim(x repository.Bibliography)map[string]any{return map[string]any{"id":x.ID,"titulo":x.Titulo,"autores":x.Autores,"año":x.Anio,"tipo":x.Tipo,"editorial":deref(x.Editorial),"resumen":deref(x.Resumen),"url":deref(x.URL),"articulos_relacionados":[]string{},"visible":x.Visible}}
func servicesCatalogDTOShim(x repository.Catalog,items []repository.CatalogItem)map[string]any{return map[string]any{"id":x.ID,"titulo":x.Titulo,"descripcion":deref(x.Descripcion),"imagen_portada":deref(x.ImagenPortada),"categorias_disponibles":map[string]any{},"elementos":items,"visible":x.Visible}}
func servicesAdDTOShim(x repository.Ad)map[string]any{return map[string]any{"id":x.ID,"imagen":deref(x.Imagen),"imagen_alt":deref(x.ImagenAlt),"contacto":deref(x.Contacto),"slogan":deref(x.Slogan),"descripcion":deref(x.Descripcion),"vigencia_inicio":nil,"vigencia_fin":nil,"activo":x.Activo,"peso":x.Peso,"enlace":deref(x.Enlace),"tipo":x.Tipo,"paginas":x.Paginas,"prioridad_slot":deref(x.PrioridadSlot)}}
func deref(v *string)any{if v==nil{return nil};return *v}
